
version: '3.8'
services:
  kong-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migration:
    image: kong:3.4
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
    depends_on:
      - kong-database

  kong:
    image: kong:3.4
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_DATABASE=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - kong-migration

  user-service:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./services/user-service/nginx.conf:/etc/nginx/nginx.conf
      - ./services/user-service/html:/usr/share/nginx/html

  product-service:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./services/product-service/nginx.conf:/etc/nginx/nginx.conf
      - ./services/product-service/html:/usr/share/nginx/html

  order-service:
    image: nginx:alpine
    ports:
      - "3003:80"
    volumes:
      - ./services/order-service/nginx.conf:/etc/nginx/nginx.conf
      - ./services/order-service/html:/usr/share/nginx/html

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  kong_data:
