
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    env_file: ./wordpress/.env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file: ./mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file: ./phpmyadmin/.env
    depends_on:
      - mysql

volumes:
  wordpress_data:
  mysql_data:
