
version: '3.8'
services:
  nextcloud:
    image: nextcloud:latest
    ports:
      - "8080:80"
    env_file: ./nextcloud/.env
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file: ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  nextcloud_data:
  postgres_data:
